Add best practices of Typescript
saiprasad2595/typescript-best-practices pull request #3
Opened 2018-10-10 12:45 UTC by GOVINDDIXIT

2018-10-10 12:50 UTC, GOVINDDIXIT commented
@saiprasad2595  pls review

2018-10-11 08:05 UTC, GOVINDDIXIT commented
@saiprasad2595  should I add more. I thought I should leave something for others as it is a hacktoberfest issue

2018-10-11 08:10 UTC, saiprasad2595 commented
@GOVINDDIXIT I have given review comments pls check.

2018-10-11 08:13 UTC, GOVINDDIXIT commented
Where, they are not visible in the thread

2018-10-11 08:18 UTC, saiprasad2595 requested changes

2018-10-11 08:18 UTC, saiprasad2595 commented on README.md
> +interface Something {
Needs some description. Writing down just a function in interface does not mean anything.

2018-10-11 08:18 UTC, saiprasad2595 commented on README.md
> +declare function duration(): number;
I do think so this is a good way of declaring function separately. If yes please give an example and say why it is a good practice.

2018-10-11 08:33 UTC, GOVINDDIXIT commented
I think these changes will be more easy to understand

2018-10-14 13:33 UTC, GOVINDDIXIT commented
@saiprasad2595 pls review

2018-10-14 13:43 UTC, saiprasad2595 approved these changes

2018-10-14 13:44 UTC, merged

2018-10-14 13:45 UTC, saiprasad2595 commented
Thanks for your time. Sorry for the delay I was sick. Keep loving OS 😀